/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lv.rigacoding.blackjack;

import Data.Card;
import Data.Game;
import graphics.CardImage;
import graphics.CardHolder;
/**
 *
 * @author Madza
 */
public class BlackJeckForm extends javax.swing.JFrame {
    private CardHolder playerCards;
    private CardHolder dealerCards;
    private Game game;
    
    public BlackJeckForm() {
        initComponents();
        
        playerCards = new CardHolder();
        dealerCards = new CardHolder();

        
        
        this.playerPanel2.add(playerCards);
        this.dealerPanel.add(dealerCards);
        
        game = new Game();
        game.startNewGameUI();
        
        
        refreshTable(false);
        startGame();
    }
    
    private void startGame(){
        game.startNewGameUI();
        
        refreshTable(false);
        
        InformationLabel.setVisible(false);
        playAgainButton.setVisible(false);
        
        dealerPointsLabel.setText("Dīlera punkti");
        stopButton.setVisible(true);
        dealerCardButton.setVisible(true);
    }
    
    private void refreshTable(boolean isFinish){
        playerCards.clear();
        dealerCards.clear();
        
        for(Card card : game.player.getCards()){
            playerCards.addCard(new CardImage(card));
        }
        
        for(Card card : game.dealer.getCards()){
            if(isFinish){
            card.isBlind = false;
        }
            dealerCards.addCard(new CardImage(card));
        }
        
        playersPointsLabel.setText("Punkti: " + game.player.getTotalPoints());
        if(isFinish){
            dealerPointsLabel.setText("Punkti: " + game.dealer.getTotalPoints());
        }
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealerPanel = new javax.swing.JPanel();
        playerPanel2 = new javax.swing.JPanel();
        playersPointsLabel = new javax.swing.JLabel();
        dealerCardButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        dealerPointsLabel = new javax.swing.JLabel();
        InformationLabel = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dealerPanel.setBackground(new java.awt.Color(250, 250, 250));

        playerPanel2.setBackground(new java.awt.Color(250, 250, 250));

        playersPointsLabel.setText("Spēlētāja punkti");

        dealerCardButton.setText("Vēl kārti");
        dealerCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerCardButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Pietiek");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        dealerPointsLabel.setText("Dīlera punkti");

        InformationLabel.setText("Paziņojums");

        playAgainButton.setText("Spēlēt vēlreiz");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playersPointsLabel)
                            .addComponent(dealerPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playAgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(stopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(dealerCardButton))
                    .addComponent(dealerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(dealerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InformationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(dealerPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playAgainButton)
                    .addComponent(stopButton)
                    .addComponent(dealerCardButton))
                .addGap(20, 20, 20)
                .addComponent(playerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dealerCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerCardButtonActionPerformed
        game.giveCard(game.player,false);
        refreshTable(false);
        
        if(game.player.getTotalPoints() > 21){
            dealerCardButton.setVisible(false);
            playAgainButton.setVisible(true);
        }
    }//GEN-LAST:event_dealerCardButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        game.dealerTurn();
        refreshTable(true);
        dealerCardButton.setVisible(false);
        stopButton.setVisible(false);
        
        InformationLabel.setText(game.getResultText());
        InformationLabel.setVisible(false);
        playAgainButton.setVisible(false);
        
    }//GEN-LAST:event_stopButtonActionPerformed

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
       startGame();
    }//GEN-LAST:event_playAgainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJeckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJeckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJeckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJeckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJeckForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InformationLabel;
    private javax.swing.JButton dealerCardButton;
    private javax.swing.JPanel dealerPanel;
    private javax.swing.JLabel dealerPointsLabel;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JPanel playerPanel2;
    private javax.swing.JLabel playersPointsLabel;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
